/**
 * Represents the current state of the UI and Design System.
 * Collected by the "Current Design Gatherer".
 */
export interface DesignContext {
  /**
   * List of applications and their key routes/components.
   */
  apps: Array<{
    name: string;
    routes: string[];
    mainComponents: string[];
  }>;
  /**
   * Inventory of the Ously Design System (ODS).
   */
  ods: {
    components: string[]; // Names of components available in @ously/ui
    theme: {
      colors: Record<string, string>;
      spacing: Record<string, string>;
      typography: Record<string, string>;
    };
  };
  /**
   * High-level functional requirements or existing features.
   */
  functionality: string[];
}

/**
 * Represents a design specification generated by an external service (e.g., Stitch).
 */
export interface DesignSpec {
  id: string;
  timestamp: string;
  source: "stitch" | "manual";
  prompt: string;
  /**
   * The generated design output. Could be code snippets, markdown, or a link to a design.
   */
  output: {
    type: "code" | "markdown" | "image" | "link";
    content: string;
  };
}

/**
 * The result of matching a DesignSpec against the existing ODS.
 */
export interface DesignMatchResult {
  specId: string;
  /**
   * Analysis of components found in the design and their ODS counterparts.
   */
  matches: Array<{
    designComponentName: string;
    existingComponentName?: string; // Optional if no match found
    matchScore: number; // 0 (no match) to 1 (perfect match)
    recommendation: "reuse" | "extend" | "create";
    notes?: string;
  }>;
  /**
   * List of entirely new components that need to be added to @ously/ui.
   */
  gaps: Array<{
    name: string;
    description: string;
    priority: "high" | "medium" | "low";
  }>;
}
