"use client";

import { forwardRef, type ForwardRefExoticComponent, type RefAttributes } from "react";
import * as P from "@phosphor-icons/react";
import type { IconId } from "../const";
import { cn } from "../lib/utils";

type IconComponent = ForwardRefExoticComponent<
  { className?: string } & RefAttributes<SVGSVGElement>
>;

const iconMap: Record<IconId, IconComponent> = {
  "phosphor.arrow_left": P.ArrowLeft,
  "phosphor.arrow_right": P.ArrowRight,
  "phosphor.arrow_up": P.ArrowUp,
  "phosphor.arrow_down": P.ArrowDown,
  "phosphor.arrow_clockwise": P.ArrowClockwise,
  "phosphor.arrow_counter_clockwise": P.ArrowCounterClockwise,
  "phosphor.caret_left": P.CaretLeft,
  "phosphor.caret_right": P.CaretRight,
  "phosphor.caret_down": P.CaretDown,
  "phosphor.caret_up": P.CaretUp,
  "phosphor.caret_double_left": P.CaretDoubleLeft,
  "phosphor.caret_double_right": P.CaretDoubleRight,
  "phosphor.dots_three": P.DotsThree,
  "phosphor.dots_three_vertical": P.DotsThreeVertical,
  "phosphor.dots_three_outline": P.DotsThreeOutline,
  "phosphor.dots_three_outline_vertical": P.DotsThreeOutlineVertical,
  "phosphor.sidebar": P.Sidebar,
  "phosphor.sidebar_simple": P.SidebarSimple,
  "phosphor.house": P.House,
  "phosphor.house_simple": P.HouseSimple,
  "phosphor.house_line": P.HouseLine,
  "phosphor.chat": P.Chat,
  "phosphor.chat_circle": P.ChatCircle,
  "phosphor.chat_dots": P.ChatDots,
  "phosphor.chat_centered": P.ChatCentered,
  "phosphor.chat_teardrop": P.ChatTeardrop,
  "phosphor.envelope": P.Envelope,
  "phosphor.envelope_simple": P.EnvelopeSimple,
  "phosphor.envelope_open": P.EnvelopeOpen,
  "phosphor.phone": P.Phone,
  "phosphor.phone_call": P.PhoneCall,
  "phosphor.phone_incoming": P.PhoneIncoming,
  "phosphor.phone_outgoing": P.PhoneOutgoing,
  "phosphor.play": P.Play,
  "phosphor.pause": P.Pause,
  "phosphor.stop": P.Stop,
  "phosphor.skip_back": P.SkipBack,
  "phosphor.skip_forward": P.SkipForward,
  "phosphor.speaker_high": P.SpeakerHigh,
  "phosphor.speaker_low": P.SpeakerLow,
  "phosphor.speaker_none": P.SpeakerNone,
  "phosphor.speaker_x": P.SpeakerX,
  "phosphor.headphones": P.Headphones,
  "phosphor.microphone": P.Microphone,
  "phosphor.microphone_slash": P.MicrophoneSlash,
  "phosphor.video_camera": P.VideoCamera,
  "phosphor.video_camera_slash": P.VideoCameraSlash,
  "phosphor.music_note": P.MusicNote,
  "phosphor.music_notes": P.MusicNotes,
  "phosphor.music_note_simple": P.MusicNoteSimple,
  "phosphor.download": P.Download,
  "phosphor.download_simple": P.DownloadSimple,
  "phosphor.upload": P.Upload,
  "phosphor.upload_simple": P.UploadSimple,
  "phosphor.trash": P.Trash,
  "phosphor.trash_simple": P.TrashSimple,
  "phosphor.plus": P.Plus,
  "phosphor.minus": P.Minus,
  "phosphor.plus_circle": P.PlusCircle,
  "phosphor.minus_circle": P.MinusCircle,
  "phosphor.plus_square": P.PlusSquare,
  "phosphor.check": P.Check,
  "phosphor.check_circle": P.CheckCircle,
  "phosphor.check_square": P.CheckSquare,
  "phosphor.checks": P.Checks,
  "phosphor.pencil": P.Pencil,
  "phosphor.pencil_simple": P.PencilSimple,
  "phosphor.pencil_line": P.PencilLine,
  "phosphor.copy": P.Copy,
  "phosphor.copy_simple": P.CopySimple,
  "phosphor.scissors": P.Scissors,
  "phosphor.link": P.Link,
  "phosphor.link_simple": P.LinkSimple,
  "phosphor.link_break": P.LinkBreak,
  "phosphor.share": P.Share,
  "phosphor.share_network": P.ShareNetwork,
  "phosphor.share_fat": P.ShareFat,
  "phosphor.paper_plane_right": P.PaperPlaneRight,
  "phosphor.magnifying_glass": P.MagnifyingGlass,
  "phosphor.magnifying_glass_plus": P.MagnifyingGlassPlus,
  "phosphor.magnifying_glass_minus": P.MagnifyingGlassMinus,
  "phosphor.funnel": P.Funnel,
  "phosphor.funnel_simple": P.FunnelSimple,
  "phosphor.file": P.File,
  "phosphor.file_text": P.FileText,
  "phosphor.file_code": P.FileCode,
  "phosphor.file_image": P.FileImage,
  "phosphor.file_pdf": P.FilePdf,
  "phosphor.file_plus": P.FilePlus,
  "phosphor.file_minus": P.FileMinus,
  "phosphor.folder": P.Folder,
  "phosphor.folder_open": P.FolderOpen,
  "phosphor.folder_simple": P.FolderSimple,
  "phosphor.folder_plus": P.FolderPlus,
  "phosphor.folder_minus": P.FolderMinus,
  "phosphor.image": P.Image,
  "phosphor.image_square": P.ImageSquare,
  "phosphor.camera": P.Camera,
  "phosphor.camera_slash": P.CameraSlash,
  "phosphor.camera_rotate": P.CameraRotate,
  "phosphor.chart_bar": P.ChartBar,
  "phosphor.chart_bar_horizontal": P.ChartBarHorizontal,
  "phosphor.chart_line": P.ChartLine,
  "phosphor.chart_line_up": P.ChartLineUp,
  "phosphor.chart_pie": P.ChartPie,
  "phosphor.chart_donut": P.ChartDonut,
  "phosphor.table": P.Table,
  "phosphor.grid_four": P.GridFour,
  "phosphor.grid_nine": P.GridNine,
  "phosphor.list": P.List,
  "phosphor.list_bullets": P.ListBullets,
  "phosphor.list_dashes": P.ListDashes,
  "phosphor.list_numbers": P.ListNumbers,
  "phosphor.list_checks": P.ListChecks,
  "phosphor.database": P.Database,
  "phosphor.bell": P.Bell,
  "phosphor.bell_simple": P.BellSimple,
  "phosphor.bell_slash": P.BellSlash,
  "phosphor.bell_ringing": P.BellRinging,
  "phosphor.notification": P.Notification,
  "phosphor.info": P.Info,
  "phosphor.question": P.Question,
  "phosphor.warning": P.Warning,
  "phosphor.warning_circle": P.WarningCircle,
  "phosphor.warning_octagon": P.WarningOctagon,
  "phosphor.eye": P.Eye,
  "phosphor.eye_slash": P.EyeSlash,
  "phosphor.eye_closed": P.EyeClosed,
  "phosphor.lock": P.Lock,
  "phosphor.lock_open": P.LockOpen,
  "phosphor.lock_simple": P.LockSimple,
  "phosphor.lock_key": P.LockKey,
  "phosphor.gear": P.Gear,
  "phosphor.gear_six": P.GearSix,
  "phosphor.wrench": P.Wrench,
  "phosphor.paint_brush": P.PaintBrush,
  "phosphor.paint_bucket": P.PaintBucket,
  "phosphor.paint_brush_broad": P.PaintBrushBroad,
  "phosphor.palette": P.Palette,
  "phosphor.swatches": P.Swatches,
  "phosphor.eraser": P.Eraser,
  "phosphor.text_t": P.TextT,
  "phosphor.text_aa": P.TextAa,
  "phosphor.text_b": P.TextB,
  "phosphor.text_italic": P.TextItalic,
  "phosphor.text_underline": P.TextUnderline,
  "phosphor.text_strikethrough": P.TextStrikethrough,
  "phosphor.text_align_left": P.TextAlignLeft,
  "phosphor.text_align_center": P.TextAlignCenter,
  "phosphor.text_align_right": P.TextAlignRight,
  "phosphor.text_align_justify": P.TextAlignJustify,
  "phosphor.sun": P.Sun,
  "phosphor.sun_dim": P.SunDim,
  "phosphor.sun_horizon": P.SunHorizon,
  "phosphor.moon": P.Moon,
  "phosphor.moon_stars": P.MoonStars,
  "phosphor.cloud": P.Cloud,
  "phosphor.cloud_check": P.CloudCheck,
  "phosphor.cloud_rain": P.CloudRain,
  "phosphor.cloud_sun": P.CloudSun,
  "phosphor.cloud_lightning": P.CloudLightning,
  "phosphor.cloud_snow": P.CloudSnow,
  "phosphor.cloud_fog": P.CloudFog,
  "phosphor.rainbow": P.Rainbow,
  "phosphor.map_pin": P.MapPin,
  "phosphor.map_pin_line": P.MapPinLine,
  "phosphor.map_pin_simple": P.MapPinSimple,
  "phosphor.map_trifold": P.MapTrifold,
  "phosphor.globe": P.Globe,
  "phosphor.globe_simple": P.GlobeSimple,
  "phosphor.globe_hemisphere_west": P.GlobeHemisphereWest,
  "phosphor.compass": P.Compass,
  "phosphor.navigation_arrow": P.NavigationArrow,
  "phosphor.car": P.Car,
  "phosphor.car_simple": P.CarSimple,
  "phosphor.bus": P.Bus,
  "phosphor.truck": P.Truck,
  "phosphor.airplane": P.Airplane,
  "phosphor.building": P.Building,
  "phosphor.buildings": P.Buildings,
  "phosphor.warehouse": P.Warehouse,
  "phosphor.factory": P.Factory,
  "phosphor.bank": P.Bank,
  "phosphor.shopping_bag": P.ShoppingBag,
  "phosphor.shopping_bag_open": P.ShoppingBagOpen,
  "phosphor.shopping_cart": P.ShoppingCart,
  "phosphor.storefront": P.Storefront,
  "phosphor.tag": P.Tag,
  "phosphor.tag_simple": P.TagSimple,
  "phosphor.wallet": P.Wallet,
  "phosphor.credit_card": P.CreditCard,
  "phosphor.currency_circle_dollar": P.CurrencyCircleDollar,
  "phosphor.coin": P.Coin,
  "phosphor.coins": P.Coins,
  "phosphor.receipt": P.Receipt,
  "phosphor.ticket": P.Ticket,
  "phosphor.money": P.Money,
  "phosphor.shield": P.Shield,
  "phosphor.shield_check": P.ShieldCheck,
  "phosphor.shield_star": P.ShieldStar,
  "phosphor.shield_warning": P.ShieldWarning,
  "phosphor.key": P.Key,
  "phosphor.key_return": P.KeyReturn,
  "phosphor.monitor": P.Monitor,
  "phosphor.laptop": P.Laptop,
  "phosphor.desktop": P.Desktop,
  "phosphor.desktop_tower": P.DesktopTower,
  "phosphor.device_mobile": P.DeviceMobile,
  "phosphor.device_tablet": P.DeviceTablet,
  "phosphor.keyboard": P.Keyboard,
  "phosphor.mouse": P.Mouse,
  "phosphor.mouse_simple": P.MouseSimple,
  "phosphor.printer": P.Printer,
  "phosphor.battery_high": P.BatteryHigh,
  "phosphor.battery_medium": P.BatteryMedium,
  "phosphor.battery_low": P.BatteryLow,
  "phosphor.battery_full": P.BatteryFull,
  "phosphor.battery_empty": P.BatteryEmpty,
  "phosphor.battery_charging": P.BatteryCharging,
  "phosphor.wifi_high": P.WifiHigh,
  "phosphor.wifi_medium": P.WifiMedium,
  "phosphor.wifi_low": P.WifiLow,
  "phosphor.wifi_slash": P.WifiSlash,
  "phosphor.bluetooth": P.Bluetooth,
  "phosphor.plug": P.Plug,
  "phosphor.plug_charging": P.PlugCharging,
  "phosphor.power": P.Power,
  "phosphor.user": P.User,
  "phosphor.users": P.Users,
  "phosphor.users_three": P.UsersThree,
  "phosphor.users_four": P.UsersFour,
  "phosphor.user_plus": P.UserPlus,
  "phosphor.user_minus": P.UserMinus,
  "phosphor.user_check": P.UserCheck,
  "phosphor.user_circle": P.UserCircle,
  "phosphor.user_square": P.UserSquare,
  "phosphor.user_focus": P.UserFocus,
  "phosphor.user_rectangle": P.UserRectangle,
  "phosphor.sign_in": P.SignIn,
  "phosphor.sign_out": P.SignOut,
  "phosphor.star": P.Star,
  "phosphor.star_four": P.StarFour,
  "phosphor.star_half": P.StarHalf,
  "phosphor.heart": P.Heart,
  "phosphor.heart_break": P.HeartBreak,
  "phosphor.heart_straight": P.HeartStraight,
  "phosphor.calendar": P.Calendar,
  "phosphor.calendar_blank": P.CalendarBlank,
  "phosphor.calendar_check": P.CalendarCheck,
  "phosphor.calendar_x": P.CalendarX,
  "phosphor.calendar_dot": P.CalendarDot,
  "phosphor.calendar_plus": P.CalendarPlus,
  "phosphor.calendar_minus": P.CalendarMinus,
  "phosphor.clock": P.Clock,
  "phosphor.clock_afternoon": P.ClockAfternoon,
  "phosphor.clock_clockwise": P.ClockClockwise,
  "phosphor.clock_counter_clockwise": P.ClockCounterClockwise,
  "phosphor.bookmark": P.Bookmark,
  "phosphor.bookmark_simple": P.BookmarkSimple,
  "phosphor.lightning": P.Lightning,
  "phosphor.lightning_slash": P.LightningSlash,
  "phosphor.gift": P.Gift,
  "phosphor.rocket": P.Rocket,
  "phosphor.fire": P.Fire,
  "phosphor.crown": P.Crown,
  "phosphor.seal_check": P.SealCheck,
  "phosphor.medal": P.Medal,
  "phosphor.trophy": P.Trophy,
  "phosphor.code": P.Code,
  "phosphor.code_simple": P.CodeSimple,
  "phosphor.code_block": P.CodeBlock,
  "phosphor.terminal": P.Terminal,
  "phosphor.terminal_window": P.TerminalWindow,
  "phosphor.bug": P.Bug,
  "phosphor.cpu": P.Cpu,
  "phosphor.cube": P.Cube,
  "phosphor.stack": P.Stack,
  "phosphor.stack_simple": P.StackSimple,
  "phosphor.qr_code": P.QrCode,
  "phosphor.scan": P.Scan,
  "phosphor.archive": P.Archive,
  "phosphor.flag": P.Flag,
  "phosphor.flag_banner": P.FlagBanner,
  "phosphor.flag_pennant": P.FlagPennant,
  "phosphor.sliders": P.Sliders,
  "phosphor.sliders_horizontal": P.SlidersHorizontal,
  "phosphor.toggle_left": P.ToggleLeft,
  "phosphor.toggle_right": P.ToggleRight,
  "phosphor.layout": P.Layout,
  "phosphor.sparkle": P.Sparkle,
  "phosphor.x": P.X,
};

const iconSizes = {
  sm: "size-3.5",
  md: "size-4",
  lg: "size-5",
  xl: "size-6",
} as const;

const iconColors = {
  foreground: "text-foreground",
  background: "text-background",
  primary: "text-primary",
  muted: "text-muted-foreground",
} as const;

export type IconSize = keyof typeof iconSizes;
export type IconColor = keyof typeof iconColors;

export interface IconProps {
  id: IconId;
  size?: IconSize;
  color?: IconColor;
}

const Icon = forwardRef<SVGSVGElement, IconProps>(
  ({ id, size = "md", color }, ref) => {
    const Component = iconMap[id];
    return (
      <Component
        ref={ref}
        className={cn(
          "shrink-0",
          iconSizes[size],
          color && iconColors[color],
        )}
      />
    );
  },
);
Icon.displayName = "Icon";

export { Icon };
