name = "api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ously-db"
database_id = "50d47be8-dd12-4755-af1f-eee54743a3a1"

[vars]
GOOGLE_CLIENT_ID = ""
GOOGLE_CLIENT_SECRET = ""
BETTER_AUTH_URL = ""
BETTER_AUTH_SECRET = ""

[env.production]
name = "api-prod"
routes = [
	{ pattern = "api.ously.tech", custom_domain = true }
]
